name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run compile

    - name: Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Extract changelog
      id: changelog
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        # Extract the section for this version from CHANGELOG.md
        sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d' > version_changelog.txt
        # If empty, try without brackets
        if [ ! -s version_changelog.txt ]; then
          sed -n "/^## $VERSION/,/^## /p" CHANGELOG.md | sed '$d' > version_changelog.txt
        fi
        # Set as output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat version_changelog.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Package Extension
      run: |
        npm install -g @vscode/vsce
        vsce package --no-dependencies

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ steps.version.outputs.version }}
        body: |
          ## Serilog Syntax Highlighting for VS Code v${{ steps.version.outputs.version }}
          
          ${{ steps.changelog.outputs.changelog }}
          
          ### Installation
          
          **From VS Code Marketplace:**
          1. Open VS Code
          2. Go to Extensions (Ctrl+Shift+X)
          3. Search for "Serilog Syntax"
          4. Click Install
          
          **From VSIX file:**
          1. Download the `.vsix` file from the assets below
          2. In VS Code, go to Extensions (Ctrl+Shift+X)
          3. Click the "..." menu → Install from VSIX
          4. Select the downloaded file
        files: |
          *.vsix
        draft: false
        prerelease: false

  publish:
    name: Publish to Marketplace
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run compile

    - name: Publish to VS Code Marketplace
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      run: |
        npm install -g @vscode/vsce
        vsce publish -p $VSCE_TOKEN